/**
 * Full crawl: pump.science compound tokens, Molecule ipNFTs, Research Hub papers + proposals.
 *
 * From repo root: node crawlers/full-crawl.mjs
 * From crawlers/:  node full-crawl.mjs
 *
 * Crawl-log (Arweave): set AGENT_WALLET and PATH_TO_KEYFILE in repo-root .env. Before crawls,
 * the latest on-chain JSON with tag doctype=crawllog is loaded; only entries marked reviewed
 * are skipped (unreviewed items are re-crawled after ephemeral restarts). After crawls, merged
 * crawl-log.json (v2 objects with optional reviewed field)
 * (researchhub, molecule, pump.science tickers) is uploaded via
 * python -m uploader --recipe crawl-log (tags: doctype, Crawl-Date, Content-Type); receipt at
 * crawlers/output/crawl-upload-receipt.json.
 * Pass --no-upload to skip the upload step (local testing).
 *
 * Manifests (papers_manifest.json, proposals/manifest.json) are always regenerated by the
 * Python crawlers; merge still includes them when present on disk so cumulative crawl-log
 * stays consistent.
 */
import { spawnSync } from "node:child_process";
import fsSync from "node:fs";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const crawlers = __dirname;
const repoRoot = path.join(crawlers, "..");

/** Load Claim-extractor/.env into process.env (does not override existing vars). */
function loadRepoRootEnv() {
  const envPath = path.join(repoRoot, ".env");
  if (!fsSync.existsSync(envPath)) return;
  const source = fsSync.readFileSync(envPath, "utf-8");
  for (const line of source.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq <= 0) continue;
    const key = trimmed.slice(0, eq).trim();
    if (!key || process.env[key] !== undefined) continue;
    let raw = trimmed.slice(eq + 1).trim();
    if (
      (raw.startsWith('"') && raw.endsWith('"')) ||
      (raw.startsWith("'") && raw.endsWith("'"))
    ) {
      raw = raw.slice(1, -1);
    }
    process.env[key] = raw;
  }
}

loadRepoRootEnv();

const moleculeCwd = path.join(crawlers, "molecule", "crawler");
const researchHubCwd = path.join(crawlers, "research-hub");
const researchHubOut = path.join(crawlers, "output", "researchhub");
const outputDir = path.join(crawlers, "output");
const skipFilePath = path.join(outputDir, ".crawl-skip.json");
const crawlLogPath = path.join(outputDir, "crawl-log.json");
const uploadReceiptPath = path.join(outputDir, "crawl-upload-receipt.json");
const uploadMetadataPath = path.join(outputDir, "upload_metadata.json");
const moleculeIpnftsOut = path.join(crawlers, "output", "molecule", "ipnfts");
const compoundTokensPath = path.join(
  crawlers,
  "output",
  "pump.science",
  "compound-tokens.json",
);

const python = process.platform === "win32" ? "python" : "python3";

const ARWEAVE_GQL =
  process.env.ARWEAVE_GRAPHQL_URL ?? "https://arweave.net/graphql";

const GQL_CRAWL_LOG = `
query CrawlLogTxs($owners: [String!]!) {
  transactions(
    owners: $owners
    tags: [{ name: "doctype", values: ["crawllog"] }]
    first: 50
  ) {
    edges {
      node {
        id
        block {
          timestamp
        }
      }
    }
  }
}
`;

/** @returns {{ log: Record<string, unknown> | null, txId: string | null }} */
async function fetchLatestCrawlLog(agentWallet) {
  const body = JSON.stringify({
    query: GQL_CRAWL_LOG,
    variables: { owners: [agentWallet] },
  });
  let res;
  try {
    res = await fetch(ARWEAVE_GQL, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body,
    });
  } catch {
    return { log: null, txId: null };
  }
  if (!res.ok) return { log: null, txId: null };
  const parsed = await res.json();
  if (parsed.errors?.length) return { log: null, txId: null };
  const edges = parsed.data?.transactions?.edges ?? [];
  if (edges.length === 0) return { log: null, txId: null };

  let bestId = null;
  let bestTs = -1;
  for (const e of edges) {
    const n = e?.node;
    if (!n?.id) continue;
    const ts = n.block?.timestamp ?? 0;
    if (ts >= bestTs) {
      bestTs = ts;
      bestId = n.id;
    }
  }
  if (!bestId) {
    bestId = edges[0].node.id;
  }

  let dataRes;
  try {
    dataRes = await fetch(`https://arweave.net/${bestId}`);
  } catch {
    return { log: null, txId: null };
  }
  if (!dataRes.ok) return { log: null, txId: null };
  let log;
  try {
    const text = await dataRes.text();
    log = JSON.parse(text);
  } catch {
    return { log: null, txId: null };
  }
  if (!log || typeof log !== "object") return { log: null, txId: null };
  if (!Array.isArray(log.researchhub?.files) || !Array.isArray(log.molecule?.folders)) {
    return { log: null, txId: null };
  }
  return { log: normalizeCrawlLog(log), txId: bestId };
}

const REVIEWED_VALUE = "reviewed";

/** @param {unknown} entry */
function entryKey(section, entry) {
  if (typeof entry === "string") return entry.trim() || null;
  if (!entry || typeof entry !== "object") return null;
  if (section === "researchhub") {
    return String(/** @type {{ path?: string }} */ (entry).path ?? "").trim() || null;
  }
  if (section === "molecule") {
    return String(/** @type {{ name?: string }} */ (entry).name ?? "").trim() || null;
  }
  if (section === "pumpScience") {
    return String(/** @type {{ ticker?: string }} */ (entry).ticker ?? "").trim() || null;
  }
  return null;
}

/** @param {unknown} entry */
function isReviewedEntry(entry) {
  if (!entry || typeof entry !== "object") return false;
  return /** @type {{ reviewed?: string }} */ (entry).reviewed === REVIEWED_VALUE;
}

/** @param {string} section @param {string} key @param {boolean} reviewed */
function makeEntry(section, key, reviewed = false) {
  /** @type {Record<string, string>} */
  const entry =
    section === "researchhub"
      ? { path: key }
      : section === "molecule"
        ? { name: key }
        : { ticker: key };
  if (reviewed) entry.reviewed = REVIEWED_VALUE;
  return entry;
}

/** @param {string} section @param {unknown[]} entries */
function normalizeEntries(section, entries) {
  /** @type {Map<string, Record<string, string>>} */
  const byKey = new Map();
  for (const raw of entries) {
    const key = entryKey(section, raw);
    if (!key) continue;
    const reviewed = isReviewedEntry(raw);
    const existing = byKey.get(key);
    if (!existing) {
      byKey.set(key, makeEntry(section, key, reviewed));
    } else if (reviewed) {
      existing.reviewed = REVIEWED_VALUE;
    }
  }
  return [...byKey.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([, v]) => v);
}

/** @param {Record<string, unknown>} log */
function normalizeCrawlLog(log) {
  const out = { ...log, version: 2 };
  if (Array.isArray(log.researchhub?.files)) {
    out.researchhub = {
      .../** @type {object} */ (log.researchhub),
      files: normalizeEntries("researchhub", log.researchhub.files),
    };
  }
  if (Array.isArray(log.molecule?.folders)) {
    out.molecule = {
      .../** @type {object} */ (log.molecule),
      folders: normalizeEntries("molecule", log.molecule.folders),
    };
  }
  if (Array.isArray(log.pumpScience?.tickers)) {
    out.pumpScience = {
      .../** @type {object} */ (log.pumpScience),
      tickers: normalizeEntries("pumpScience", log.pumpScience.tickers),
    };
  }
  return out;
}

/** @param {string} section @param {unknown[]} entries */
function reviewedKeys(section, entries) {
  return normalizeEntries(section, entries)
    .filter((e) => e.reviewed === REVIEWED_VALUE)
    .map((e) => entryKey(section, e))
    .filter(Boolean);
}

async function writeCrawlSkipFile(absPath, log) {
  const moleculeFolders = reviewedKeys("molecule", log?.molecule?.folders ?? []);
  const researchhubFiles = reviewedKeys("researchhub", log?.researchhub?.files ?? []);
  const pumpScienceTickers = reviewedKeys(
    "pumpScience",
    log?.pumpScience?.tickers ?? [],
  );
  await fs.mkdir(path.dirname(absPath), { recursive: true });
  await fs.writeFile(
    absPath,
    JSON.stringify(
      { moleculeFolders, researchhubFiles, pumpScienceTickers },
      null,
      2,
    ),
    "utf-8",
  );
}

async function listResearchhubRelativeFiles(rhRoot) {
  const out = [];
  for (const sub of ["papers", "proposals"]) {
    const dir = path.join(rhRoot, sub);
    let names;
    try {
      names = await fs.readdir(dir);
    } catch {
      continue;
    }
    for (const n of names) {
      const full = path.join(dir, n);
      let st;
      try {
        st = await fs.stat(full);
      } catch {
        continue;
      }
      if (st.isFile()) out.push(`${sub}/${n}`.replace(/\\/g, "/"));
    }
  }
  return out.sort();
}

async function listMoleculeTopFolders(ipnftsRoot) {
  let entries;
  try {
    entries = await fs.readdir(ipnftsRoot, { withFileTypes: true });
  } catch {
    return [];
  }
  return entries
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();
}

async function listPumpScienceTickers(tokensPath) {
  try {
    const tokens = JSON.parse(await fs.readFile(tokensPath, "utf-8"));
    if (!Array.isArray(tokens)) return [];
    return [
      ...new Set(
        tokens.map((t) => String(t.ticker ?? "").trim()).filter(Boolean),
      ),
    ].sort();
  } catch {
    return [];
  }
}

async function loadPumpScienceSkipTickers(skipPath) {
  try {
    const data = JSON.parse(await fs.readFile(skipPath, "utf-8"));
    const arr = data.pumpScienceTickers ?? [];
    if (!Array.isArray(arr)) return new Set();
    return new Set(arr.map((t) => String(t).trim()).filter(Boolean));
  } catch {
    return new Set();
  }
}

/** @returns {{ total: number, kept: number, skipped: number }} */
async function filterCompoundTokensByCrawlLog(tokensPath, skipPath) {
  const skip = await loadPumpScienceSkipTickers(skipPath);
  let tokens;
  try {
    tokens = JSON.parse(await fs.readFile(tokensPath, "utf-8"));
  } catch {
    return { total: 0, kept: 0, skipped: 0 };
  }
  if (!Array.isArray(tokens)) {
    return { total: 0, kept: 0, skipped: 0 };
  }
  const total = tokens.length;
  const kept = tokens.filter((t) => {
    const ticker = String(t.ticker ?? "").trim();
    return ticker && !skip.has(ticker);
  });
  await fs.writeFile(tokensPath, JSON.stringify(kept, null, 2), "utf-8");
  return { total, kept: kept.length, skipped: total - kept.length };
}

function mergeCrawlLog(
  previousLog,
  diskFiles,
  diskFolders,
  diskTickers,
  previousTxId,
) {
  const prev = previousLog ? normalizeCrawlLog(previousLog) : null;
  const prevFileMap = new Map(
    normalizeEntries("researchhub", prev?.researchhub?.files ?? []).map((e) => [
      entryKey("researchhub", e),
      e,
    ]),
  );
  const prevFolderMap = new Map(
    normalizeEntries("molecule", prev?.molecule?.folders ?? []).map((e) => [
      entryKey("molecule", e),
      e,
    ]),
  );
  const prevTickerMap = new Map(
    normalizeEntries("pumpScience", prev?.pumpScience?.tickers ?? []).map((e) => [
      entryKey("pumpScience", e),
      e,
    ]),
  );

  for (const path of diskFiles) {
    if (!prevFileMap.has(path)) prevFileMap.set(path, makeEntry("researchhub", path));
  }
  for (const name of diskFolders) {
    if (!prevFolderMap.has(name)) prevFolderMap.set(name, makeEntry("molecule", name));
  }
  for (const ticker of diskTickers) {
    if (!prevTickerMap.has(ticker)) {
      prevTickerMap.set(ticker, makeEntry("pumpScience", ticker));
    }
  }

  const files = [...prevFileMap.values()].sort((a, b) =>
    (entryKey("researchhub", a) ?? "").localeCompare(entryKey("researchhub", b) ?? ""),
  );
  const folders = [...prevFolderMap.values()].sort((a, b) =>
    (entryKey("molecule", a) ?? "").localeCompare(entryKey("molecule", b) ?? ""),
  );
  const tickers = [...prevTickerMap.values()].sort((a, b) =>
    (entryKey("pumpScience", a) ?? "").localeCompare(entryKey("pumpScience", b) ?? ""),
  );

  return {
    version: 2,
    updatedAt: new Date().toISOString(),
    previousArweaveTxId: previousTxId ?? null,
    researchhub: { files },
    molecule: { folders },
    pumpScience: { tickers },
  };
}

const noUpload = process.argv.includes("--no-upload");

const agentWallet = process.env.AGENT_WALLET?.trim();

let previousLog = null;
let previousTxId = null;
if (agentWallet) {
  const r = await fetchLatestCrawlLog(agentWallet);
  previousLog = r.log;
  previousTxId = r.txId;
  console.error(
    previousTxId
      ? `[crawl-log] Loaded previous log from tx ${previousTxId}`
      : "[crawl-log] No previous crawl-log on chain (cold start or fetch failed).",
  );
  await writeCrawlSkipFile(skipFilePath, previousLog ?? {});
} else {
  console.error(
    "[crawl-log] AGENT_WALLET unset — skipping remote log fetch; no incremental skip.",
  );
  await fs.mkdir(outputDir, { recursive: true });
  await writeCrawlSkipFile(skipFilePath, {});
}

const skipArg = skipFilePath;
const pumpScienceFetch = path.join(crawlers, "pump-science", "fetch-compound-tokens.sh");

const steps = [
  {
    label: "pump.science: compound tokens",
    cwd: crawlers,
    cmd: "bash",
    args: [pumpScienceFetch],
    shell: false,
    filterPumpScience: true,
  },
  {
    label: "molecule: crawl (profiles + data-bundle)",
    cwd: moleculeCwd,
    cmd: "npm",
    args: [
      "run",
      "cli",
      "--",
      "crawl",
      "--output-dir",
      "@crawlers/output/molecule/ipnfts",
      "--competent-only",
      "--crawl-skip-file",
      skipArg,
    ],
    shell: process.platform === "win32",
  },
  {
    label: "research-hub: crawl-for-review.py",
    cwd: researchHubCwd,
    cmd: python,
    args: [
      "crawl-for-review.py",
      "--output-dir",
      researchHubOut,
      "--crawl-skip-file",
      skipArg,
    ],
    shell: false,
  },
];

for (const step of steps) {
  console.error(`\n=== ${step.label} ===\n`);
  const r = spawnSync(step.cmd, step.args, {
    cwd: step.cwd,
    stdio: "inherit",
    env: process.env,
    shell: step.shell,
  });
  if (r.error) {
    console.error(r.error);
    process.exit(1);
  }
  if (r.signal) {
    console.error(`\nStopped: "${step.label}" killed by signal ${r.signal}.`);
    process.exit(1);
  }
  const code = typeof r.status === "number" ? r.status : 1;
  if (code !== 0) {
    console.error(`\nStopped: "${step.label}" exited with ${code}.`);
    process.exit(code);
  }
  if (step.filterPumpScience) {
    const stats = await filterCompoundTokensByCrawlLog(
      compoundTokensPath,
      skipFilePath,
    );
    console.error(
      `[pump.science] ${stats.kept} new ticker(s), ${stats.skipped} skipped (crawl_log) of ${stats.total} fetched`,
    );
  }
}

const diskRh = await listResearchhubRelativeFiles(researchHubOut);
const diskMol = await listMoleculeTopFolders(moleculeIpnftsOut);
const diskTickers = await listPumpScienceTickers(compoundTokensPath);
const merged = mergeCrawlLog(
  previousLog,
  diskRh,
  diskMol,
  diskTickers,
  previousTxId,
);
await fs.mkdir(outputDir, { recursive: true });
await fs.writeFile(crawlLogPath, JSON.stringify(merged, null, 2), "utf-8");
console.error(
  `\n[crawl-log] Wrote ${crawlLogPath} (+${diskTickers.length} new pump.science ticker(s) this run)`,
);

if (noUpload) {
  console.error("[crawl-log] --no-upload: skipping Arweave upload.");
} else {
  const uploadArgs = [
    "-m",
    "uploader",
    "--recipe",
    "crawl-log",
    "--file",
    crawlLogPath,
    "--output-dir",
    outputDir,
  ];
  console.error("\n=== crawl-log: upload to Arweave ===\n");
  const up = spawnSync(python, uploadArgs, {
    cwd: repoRoot,
    encoding: "utf-8",
    env: process.env,
    shell: false,
  });
  if (up.error) {
    console.error(up.error);
    process.exit(1);
  }
  const stdout = up.stdout ?? "";
  const stderr = up.stderr ?? "";
  let txId = null;
  let webUrl = null;
  if (fsSync.existsSync(uploadMetadataPath)) {
    try {
      const metadata = JSON.parse(
        fsSync.readFileSync(uploadMetadataPath, "utf-8"),
      );
      txId = metadata.crawl_log?.txid ?? null;
      webUrl = metadata.crawl_log?.url ?? null;
    } catch {
      // ignore malformed metadata; receipt will reflect failure
    }
  }
  const exitCode = typeof up.status === "number" ? up.status : 1;
  const success = webUrl !== null && exitCode === 0;
  await fs.mkdir(path.dirname(uploadReceiptPath), { recursive: true });
  await fs.writeFile(
    uploadReceiptPath,
    `${JSON.stringify(
      {
        success,
        uploaded_file: crawlLogPath,
        tx_id: txId,
        web_url: webUrl,
        cli_stdout: stdout,
        cli_stderr: stderr,
        exit_code: exitCode,
        cli_command: [python, ...uploadArgs],
      },
      null,
      2,
    )}\n`,
    "utf-8",
  );
  console.error(`[crawl-log] Receipt: ${uploadReceiptPath}`);
  if (!success) {
    console.error(
      `\nStopped: crawl-log upload failed (exit ${exitCode}). See receipt stderr.`,
    );
    process.exit(1);
  }
}

console.error("\n=== full crawl finished ===\n");
